from typing import Protocol, Optional, List
from uuid import UUID

from src.chat.schemas import ChatCreate, ChatOverview, ChatSchemaFull, ChatDetail


class ChatRepositoryPort(Protocol):
    async def list_all_chats(self, limit: int = 100, offset: int = 0) -> List[object]: ...
    async def get_chat(self, chat_id: UUID) -> Optional[object]: ...
    async def get_last_message_for_chat(self, chat_id: UUID) -> Optional[object]: ...
    async def get_participants_count(self, chat_id: UUID) -> int: ...
    async def list_messages_for_chat(self, chat_id: UUID, limit: int = 200, offset: int = 0) -> List[object]: ...
    async def count_messages_for_chat(self, chat_id: UUID) -> int: ...
    async def delete_chat(self, chat_id:UUID) -> bool: ...

class ChatServicePort(Protocol):
    async def create_chat(self, payload: ChatCreate) -> ChatSchemaFull: ...
    async def list_all_chats(self, limit: int = 100, offset: int = 0) -> List[ChatOverview]: ...
    async def get_chat_detail(self, chat_id: UUID, msg_limit: int = 200, msg_offset: int = 0) -> ChatDetail: ...
    async def delete_chat(self, chat_id:UUID) -> bool: ...