from typing import Optional, Protocol
from src.personality.models import Personality


class PersonalityRepositoryPort(Protocol):
    async def add(self, personality: Personality) -> Personality: ...
    async def get_by_id(self, personality_id: int) -> Optional[Personality]: ...
    async def get_by_agent_id(self, agent_id: int) -> Optional[Personality]: ...
    async def update(self, personality: Personality) -> Personality: ...
