"""empty message

Revision ID: 01da44e226fe
Revises: 
Create Date: 2026-02-16 18:18:12.608170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '01da44e226fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('DIRECT', 'GROUP', 'SYSTEM', name='chattype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('world_timestamp_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('currentmood',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('joy', sa.Float(), nullable=False),
    sa.Column('saddness', sa.Float(), nullable=False),
    sa.Column('anger', sa.Float(), nullable=False),
    sa.Column('fear', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currentmood_agent_id'), 'currentmood', ['agent_id'], unique=False)
    op.create_index(op.f('ix_currentmood_id'), 'currentmood', ['id'], unique=False)
    op.create_table('memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('world_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('is_summarized', sa.Boolean(), nullable=False),
    sa.Column('source_memory_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content')
    )
    op.create_index(op.f('ix_memory_agent_id'), 'memory', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memory_id'), 'memory', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_system_event', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_chat_id'), 'message', ['chat_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_table('personality',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('speech_style_id', sa.UUID(), nullable=False),
    sa.Column('friendship', sa.Float(), nullable=False),
    sa.Column('knowledge', sa.Float(), nullable=False),
    sa.Column('safety', sa.Float(), nullable=False),
    sa.Column('freedom', sa.Float(), nullable=False),
    sa.Column('openness', sa.Float(), nullable=False),
    sa.Column('extraversion', sa.Float(), nullable=False),
    sa.Column('agreebleness', sa.Float(), nullable=False),
    sa.Column('neuroticism', sa.Float(), nullable=False),
    sa.Column('conscientiousness', sa.Float(), nullable=False),
    sa.Column('background', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personality_id'), 'personality', ['id'], unique=False)
    op.create_index(op.f('ix_personality_speech_style_id'), 'personality', ['speech_style_id'], unique=False)
    op.create_table('relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_a_id', sa.UUID(), nullable=False),
    sa.Column('agent_b_id', sa.UUID(), nullable=False),
    sa.Column('affinity', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_interaction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('history_summary_text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_summary_text')
    )
    op.create_index(op.f('ix_relationship_agent_a_id'), 'relationship', ['agent_a_id'], unique=False)
    op.create_index(op.f('ix_relationship_agent_b_id'), 'relationship', ['agent_b_id'], unique=False)
    op.create_index(op.f('ix_relationship_id'), 'relationship', ['id'], unique=False)
    op.create_table('speechstyle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formality', sa.Float(), nullable=False),
    sa.Column('verbosity', sa.Float(), nullable=False),
    sa.Column('emotional_expressiveness', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speechstyle_id'), 'speechstyle', ['id'], unique=False)
    op.create_table('worldstate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_speed', sa.Float(), nullable=False),
    sa.Column('simulation_paused', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worldstate_id'), 'worldstate', ['id'], unique=False)
    op.create_table('сhatparticipant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('world_joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_сhatparticipant_agent_id'), 'сhatparticipant', ['agent_id'], unique=False)
    op.create_index(op.f('ix_сhatparticipant_chat_id'), 'сhatparticipant', ['chat_id'], unique=False)
    op.create_index(op.f('ix_сhatparticipant_id'), 'сhatparticipant', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_сhatparticipant_id'), table_name='сhatparticipant')
    op.drop_index(op.f('ix_сhatparticipant_chat_id'), table_name='сhatparticipant')
    op.drop_index(op.f('ix_сhatparticipant_agent_id'), table_name='сhatparticipant')
    op.drop_table('сhatparticipant')
    op.drop_index(op.f('ix_worldstate_id'), table_name='worldstate')
    op.drop_table('worldstate')
    op.drop_index(op.f('ix_speechstyle_id'), table_name='speechstyle')
    op.drop_table('speechstyle')
    op.drop_index(op.f('ix_relationship_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_agent_b_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_agent_a_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_personality_speech_style_id'), table_name='personality')
    op.drop_index(op.f('ix_personality_id'), table_name='personality')
    op.drop_table('personality')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_chat_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_memory_id'), table_name='memory')
    op.drop_index(op.f('ix_memory_agent_id'), table_name='memory')
    op.drop_table('memory')
    op.drop_index(op.f('ix_currentmood_id'), table_name='currentmood')
    op.drop_index(op.f('ix_currentmood_agent_id'), table_name='currentmood')
    op.drop_table('currentmood')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
