"""empty message

Revision ID: 06ee7ae8ed82
Revises: f13402f0e6a9
Create Date: 2026-02-17 18:52:40.329029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ee7ae8ed82'
down_revision: Union[str, Sequence[str], None] = 'f13402f0e6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('involved_agents', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('world_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_type'), 'event', ['type'], unique=False)
    op.create_index(op.f('ix_event_world_timestamp'), 'event', ['world_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_world_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_type'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
