"""empty message

Revision ID: 6c6e2f614d3f
Revises: e377a5205db3
Create Date: 2026-02-18 14:04:10.412736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6e2f614d3f'
down_revision: Union[str, Sequence[str], None] = 'e377a5205db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('ai_model', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'ai_model')
    # ### end Alembic commands ###
