"""empty message

Revision ID: 824d72ba0b44
Revises: 01da44e226fe
Create Date: 2026-02-16 23:10:33.314102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824d72ba0b44'
down_revision: Union[str, Sequence[str], None] = '01da44e226fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personality_id', sa.UUID(), nullable=False),
    sa.Column('current_mood_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('current_plan', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_agent_current_mood_id'), 'agent', ['current_mood_id'], unique=False)
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index(op.f('ix_agent_personality_id'), 'agent', ['personality_id'], unique=False)
    op.add_column('currentmood', sa.Column('sadness', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_currentmood_agent_id'), table_name='currentmood')
    op.drop_column('currentmood', 'agent_id')
    op.drop_column('currentmood', 'saddness')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currentmood', sa.Column('saddness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('currentmood', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_currentmood_agent_id'), 'currentmood', ['agent_id'], unique=False)
    op.drop_column('currentmood', 'sadness')
    op.drop_index(op.f('ix_agent_personality_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_current_mood_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
