"""empty message

Revision ID: b1d9fd067739
Revises: 6c6e2f614d3f
Create Date: 2026-02-18 14:35:57.195228

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b1d9fd067739'
down_revision: Union[str, Sequence[str], None] = '6c6e2f614d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory', 'embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    op.alter_column('message', 'embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'embedding',
               existing_type=Vector(dim=1536),
               nullable=False)
    op.alter_column('memory', 'embedding',
               existing_type=Vector(dim=1536),
               nullable=False)
    # ### end Alembic commands ###
