"""empty message

Revision ID: e326d5299deb
Revises: 06ee7ae8ed82
Create Date: 2026-02-17 19:46:27.350864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e326d5299deb'
down_revision: Union[str, Sequence[str], None] = '06ee7ae8ed82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currentmood', sa.Column('color', sa.String(), nullable=False, server_default='#ffffff'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currentmood', 'color')
    # ### end Alembic commands ###
