"""empty message

Revision ID: e377a5205db3
Revises: e326d5299deb
Create Date: 2026-02-18 05:41:37.888718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e377a5205db3'
down_revision: Union[str, Sequence[str], None] = 'e326d5299deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatparticipant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('world_joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatparticipant_agent_id'), 'chatparticipant', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chatparticipant_chat_id'), 'chatparticipant', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chatparticipant_id'), 'chatparticipant', ['id'], unique=False)
    op.drop_index(op.f('ix_сhatparticipant_agent_id'), table_name='сhatparticipant')
    op.drop_index(op.f('ix_сhatparticipant_chat_id'), table_name='сhatparticipant')
    op.drop_index(op.f('ix_сhatparticipant_id'), table_name='сhatparticipant')
    op.drop_table('сhatparticipant')
    op.alter_column('currentmood', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'#ffffff'::character varying"))
    op.alter_column('memory', 'content',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_constraint(op.f('memory_content_key'), 'memory', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('memory_content_key'), 'memory', ['content'], postgresql_nulls_not_distinct=False)
    op.alter_column('memory', 'content',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('currentmood', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'#ffffff'::character varying"))
    op.create_table('сhatparticipant',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('world_joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('сhatparticipant_pkey'))
    )
    op.create_index(op.f('ix_сhatparticipant_id'), 'сhatparticipant', ['id'], unique=False)
    op.create_index(op.f('ix_сhatparticipant_chat_id'), 'сhatparticipant', ['chat_id'], unique=False)
    op.create_index(op.f('ix_сhatparticipant_agent_id'), 'сhatparticipant', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_chatparticipant_id'), table_name='chatparticipant')
    op.drop_index(op.f('ix_chatparticipant_chat_id'), table_name='chatparticipant')
    op.drop_index(op.f('ix_chatparticipant_agent_id'), table_name='chatparticipant')
    op.drop_table('chatparticipant')
    # ### end Alembic commands ###
