from typing import Protocol
from uuid import UUID

from typing import Optional, List
from src.memory.models import Memory



class MemoryRepositoryPort(Protocol):
    """Интерфейс репозитория сообщений"""
    async def add(self, memory: Memory) -> Memory: ...
    async def get_by_id(self, Memory_id: UUID) -> Optional[Memory]: ...
    async def get_all(self, active_only: bool = True, limit: int = 20) -> List[Memory]: ...
    async def delete(self, memory_id: int) -> bool: ...
    async def update(self, memory: Memory) -> Memory: ...
