from typing import Optional, Protocol
from src.speech_style.models import SpeechStyle


class SpeechStyleRepositoryPort(Protocol):
    async def add(self, speech_style: SpeechStyle) -> SpeechStyle: ...
    async def get_by_id(self, speech_style_id: int) -> Optional[SpeechStyle]: ...
    async def update(self, speech_style: SpeechStyle) -> SpeechStyle: ...
